[project]
name = "ai-search"
version = "0.0.1"
description = "AI Search Library for Zhiman AI"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
